# Generated by Django 5.2.3 on 2025-06-24 23:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cause", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(max_length=2000, verbose_name="Donor's name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=2000, verbose_name="Donor's email"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Amount donated"
                    ),
                ),
                (
                    "cause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="donations",
                        to="cause.cause",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
